### ISSUE TITLE
Add README pls

### ISSUE THREAD

**Issue by ChillerDragon** [edg-l/TeeAI#1]
whats going on here? xd
Is this a gui less tw client that should be able to play alone? o.O

**Comment by edg-l** [comment]
fixed

**Comment by ChillerDragon** [comment]
thanks c:

**Comment by ChillerDragon** [comment]
@Ryozuki any specific aspects what it should learn to play? I guess the game type will be DDNet. But solo? gores? dummy drag ? with others AIs? with humans?

Or don't you have specific plans yet?

BTW: i am excited for this project c:

**Comment by edg-l** [comment]
no specific plans yet
